### ISSUE TITLE
响应式转换有问题，对于 `2xl:`

### ISSUE THREAD

**Issue by seepine** [uni-helper/vite-plugin-uni-tailwind#32]
### 描述问题
`2xl:xxx`转换后会有 `\` 符号
```css
@media (min-width: 1280px) {
  .xl_grid-cols-5 {
    grid-template-columns: repeat(5, minmax(0, 1fr));
  }
}
@media (min-width: 1536px) {
  .\32xl_grid-cols-6 {
    grid-template-columns: repeat(6, minmax(0, 1fr));
  }
}
```
<img width="438" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-tailwind/assets/93666053/f1be200f-3634-446d-a55a-a20046e518ae">

### 复现

```vue
<view
      class="grid grid-cols-1 gap-4 p-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6"
    >
```

### 系统信息

```Shell
macos
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。
